version: '3'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    ports:
      - 3306:3306
